# 1.Каким будет результат выполнения следующего кода:
def func():
	num = 1

func()
# print(num) # вернется ошибка, переменная неизвестна во внешнем коде

# 2.Каким будет результат выполнения следующего кода:
def func():
	num = 3
	print(num)

func() # 3

# 3.Каким будет результат выполнения следующего кода:
def func():
	num = 5
	return num

print(func()) # 5

# 4.Каким будет результат выполнения следующего кода:
def func():
	num = 7
	return num

func()
# print(num) # вернется ошибка, переменная неизвестна во внешнем коде